from appium.webdriver.common.touch_action import TouchAction
from model.common_fun import Common
from selenium.webdriver.common.by import By
from time import sleep

class LoginView(Common):


    def login_action(self,username):
        print("---------------------logga in------------------------------")
        actions = TouchAction(self.driver)
        Field = self.find_element(By.XPATH,"//XCUIElementTypeStaticText[@name='Ange din e-postadress']/following-sibling::XCUIElementTypeOther[1]/XCUIElementTypeTextField")
        Field.clear()
        actions.tap(Field)
        Field.set_value(username)
        goon=self.driver.find_element_by_accessibility_id("Fortsätt")
        actions.tap(goon)
        actions.perform()
        sleep(2)
        textField=self.driver.find_element_by_ios_predicate("type =='XCUIElementTypeSecureTextField' ")
        actions.tap(textField)
        actions.perform()
        more=self.driver.find_element_by_accessibility_id("more")
        actions.tap(more)
        actions.perform()
        sleep(2)
        keyboard1=self.driver.find_element_by_accessibility_id("1")
        actions.tap(keyboard1)
        actions.perform()
        keyboard2 =self.driver.find_element_by_accessibility_id("2")
        actions.tap(keyboard2)
        actions.perform()
        keyboard5 =self.driver.find_element_by_accessibility_id("5")
        actions.tap(keyboard5)
        actions.perform()
        keyboard8 =self.driver.find_element_by_accessibility_id("8")
        actions.tap(keyboard8)
        actions.perform()
        keyboard0 =self.driver.find_element_by_accessibility_id("0")
        actions.tap(keyboard0)
        actions.perform()
        keyboard3 =self.driver.find_element_by_accessibility_id("3")
        actions.tap(keyboard3)
        actions.perform()
        keyboard6 =self.driver.find_element_by_accessibility_id("6")
        actions.tap(keyboard6)
        actions.perform()
        keyboard3 =self.driver.find_element_by_accessibility_id("3")
        actions.tap(keyboard3)
        actions.perform()
        keyboard6 =self.driver.find_element_by_accessibility_id("6")
        actions.tap(keyboard6)
        actions.perform()
        sleep(1)
        more = self.driver.find_element_by_accessibility_id("more")
        actions.tap(more)
        actions.perform()
        keyboardj=self.driver.find_element_by_accessibility_id("j")
        actions.tap(keyboardj)
        actions.perform()
        keyboardx=self.driver.find_element_by_accessibility_id("x")
        actions.tap(keyboardx)
        actions.perform()
        sleep(2)
        fortsatt=self.driver.find_element_by_ios_predicate("type =='XCUIElementTypeButton' AND label='Fortsätt' ")
        actions.tap(fortsatt)
        actions.perform()
        sleep(2)

    def login_action_sendkeys(self,username,password):
            print("---------------------logga in------------------------------")
            Field = self.find_element(By.XPATH,"//XCUIElementTypeStaticText[@name='Ange din e-postadress']/following-sibling::XCUIElementTypeOther[1]/XCUIElementTypeTextField")
            actions = TouchAction(self.driver)
            Field.clear()
            actions.tap(Field)
            Field.set_value(username)
            goon = self.driver.find_element_by_accessibility_id("Fortsätt")
            actions.tap(goon)
            actions.perform()
            textField = self.driver.find_element_by_ios_predicate("type =='XCUIElementTypeSecureTextField' ")
            actions.tap(textField)
            textField.set_value(password)
            fortsatt = self.driver.find_element_by_ios_predicate("type =='XCUIElementTypeButton' AND label='Fortsätt' ")
            actions.tap(fortsatt)
            actions.perform()
            sleep(2)

    def logout_action(self,name):
        actions = TouchAction(self.driver)
        bottom_button=self.driver.find_element_by_accessibility_id(name)
        actions.tap(bottom_button)
        actions.perform()
        sleep(2)
        print('----------------------Tryck på setting för att logga ut --------------- ')
        settings=self.driver.find_element_by_accessibility_id("icn settings")
        actions.tap(settings)
        actions.perform()
        sleep(2)
        self.swipeup()
        self.swipeup()
        self.swipeup()
        logout=self.driver.find_element_by_accessibility_id("Logga ut")
        actions.tap(logout)
        actions.perform()




